# Make a table of the data 

THis script pulls from the outputs of ghcnd_station_download_v1.0 and ENSO_indicies_download_v1.0  
Places station obs a rows and taget variables + indicies as columns

This script take daily observation data from station_data/ghcnd/all_station_data.csv  
and index data from indicies_data/first_pass/enso_historical_indicies.csv  
Then makes a built-out version of the table at the bottom of this page-> https://www.dnr.state.mn.us/climate/journal/el-nino-2026.html  

Note: averaging stations gives a 'station average' not necesarilly a 'Minnesota average'  
    more stations will decrease the difference between the two  

v0.0 designates this is a work in progress  
v1.0 should contribute to a reproducible workflow on any machine with the other 1.0 notebooks

In [47]:
import pandas as pd
from pathlib import Path
import nbformat

In [37]:
# uncomment and run this cell to make data if needed
# %run enso_indicies_download_v1.0.ipynb
# %run ghcnd_station_download_v1.0.ipynb

## Preprocessing
The code below make a raw data table that combines station data and ENSO indicies data.  
It also filters out rows with no observations.

In [55]:
#assign data to vars for pandas
indicies_data=Path('../indicies_data/first_pass/enso_historical_indicies.csv')
station_data=Path("../station_data/ghcnd/all_station_data.csv")

#read data into the dataframe

#used for run identification 
indicies_data_df_forfunction=pd.read_csv(indicies_data, skiprows=0,parse_dates=['Date']
                                                        )
#el nino index vals
indicies_data_df=pd.read_csv(
    indicies_data,
    skiprows=0,
    parse_dates=['Date']
)

#staion vals
stations_data_df=pd.read_csv(
    station_data,
    skiprows=0,
    parse_dates=['time']
)

#discard rows with no obs
stations_data_df=stations_data_df.dropna(
    subset=["TMAX", "TMIN", "PRCP", "MDPR", "DAPR",
               "SNOW", "MDSF", "DASF", "SNWD", "WESD", "WESF"],
    how='all'
)

In [39]:
#create a key they can be joined on
indicies_data_df['Month']=indicies_data_df['Date'].dt.to_period('M')
stations_data_df['Month']=stations_data_df['time'].dt.to_period('M')

In [40]:
#join the tables by date

station_obs_enso_indicies= pd.merge(
    left=stations_data_df,
    right=indicies_data_df,
    on='Month',
    how='left',
    validate='many_to_one'
)

In [41]:
#BEHOLD
store_table=Path('../outputs')
store_table.mkdir(parents=True, exist_ok=True)
station_obs_enso_indicies.to_csv(store_table/'station_obs_enso_indicies.csv', index=False)
display(station_obs_enso_indicies)

,station,time,TMAX,TMAX_q,TMIN,TMIN_q,PRCP,PRCP_q,MDPR,MDPR_q,...,lat,lon,name,winter_year,Month,Unnamed: 0,Date,ONI,RONI,TNI
0,USW00014926,1904-09-01,NaN,False,NaN,False,0.0,False,NaN,False,...,45.54416,-94.05160,"ST. CLOUD REGIONAL AIRPORT, MN US",1905,1904-09,656,1904-09-01,0.68,1.04,0.584
1,USW00014926,1904-09-02,NaN,False,NaN,False,41.4,False,NaN,False,...,45.54416,-94.05160,"ST. CLOUD REGIONAL AIRPORT, MN US",1905,1904-09,656,1904-09-01,0.68,1.04,0.584
2,USW00014926,1904-09-03,NaN,False,NaN,False,48.5,False,NaN,False,...,45.54416,-94.05160,"ST. CLOUD REGIONAL AIRPORT, MN US",1905,1904-09,656,1904-09-01,0.68,1.04,0.584
3,USW00014926,1904-09-04,NaN,False,NaN,False,0.0,False,NaN,False,...,45.54416,-94.05160,"ST. CLOUD REGIONAL AIRPORT, MN US",1905,1904-09,656,1904-09-01,0.68,1.04,0.584
4,USW00014926,1904-09-05,NaN,False,NaN,False,0.0,False,NaN,False,...,45.54416,-94.05160,"ST. CLOUD REGIONAL AIRPORT, MN US",1905,1904-09,656,1904-09-01,0.68,1.04,0.584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298952,USW00014920,2026-09-23,20.6,False,6.7,False,0.0,False,NaN,False,...,43.87922,-91.25301,"LA CROSSE REGIONAL AIRPORT, WI US",2027,2026-09,2120,2026-09-01,NaN,NaN,NaN
298953,USW00014920,2026-09-24,21.1,False,9.4,False,0.3,False,NaN,False,...,43.87922,-91.25301,"LA CROSSE REGIONAL AIRPORT, WI US",2027,2026-09,2120,2026-09-01,NaN,NaN,NaN
298954,USW00014920,2026-09-25,22.8,False,15.0,False,0.0,False,NaN,False,...,43.87922,-91.25301,"LA CROSSE REGIONAL AIRPORT, WI US",2027,2026-09,2120,2026-09-01,NaN,NaN,NaN
298955,USW00014920,2026-09-26,22.2,False,11.7,False,0.0,False,NaN,False,...,43.87922,-91.25301,"LA CROSSE REGIONAL AIRPORT, WI US",2027,2026-09,2120,2026-09-01,NaN,NaN,NaN
298956,USW00014920,2026-09-27,17.2,False,15.0,False,0.0,False,NaN,False,...,43.87922,-91.25301,"LA CROSSE REGIONAL AIRPORT, WI US",2027,2026-09,2120,2026-09-01,NaN,NaN,NaN

## Processing

The code below makes the final output of ENSO Proj Phase One

In [92]:
#pull and read data table formed above into a dataframe

raw_table=Path(r"C:\Users\wesja\Desktop\MCAP\MCAP_ENSO_PROJECT\outputs\station_obs_enso_indicies.csv")
raw_table_df=pd.read_csv(raw_table)

In [101]:
#first replace index values with Strong, Weak, etc
#starts at the highest bounds and filters downward
#currently does not support la nina detection

#helper functions

def identify_runs(df, index_column):
    months = pd.to_datetime(df['time']).dt.to_period('M')

    monthly = pd.DataFrame({
        'Month': months,
        'value': df[index_column]
    })

    index_series = (
        monthly.drop_duplicates(subset='Month')
        .set_index('Month')['value']
        .sort_index()
    )

    index_series = index_series.reindex(
        pd.period_range(
            start=index_series.index.min(),
            end=index_series.index.max(),
            freq='M'
        )
    )
    
    index_series=index_series.round(1) #this corrects the descepancy between Brian Mcnoldy calcs and NOAAs publication
    
    window_ends = (
        (index_series >= 0.5)
        .rolling(window=5)
        .sum()
        .eq(5)
    )

    episode = (
        window_ends
        | window_ends.shift(-1, fill_value=False)
        | window_ends.shift(-2, fill_value=False)
        | window_ends.shift(-3, fill_value=False)
        | window_ends.shift(-4, fill_value=False)
    )

    # A new episode starts when False changes to True
    episode_start = (
        episode & ~episode.shift(1, fill_value=False)
    )

    # Number the episodes; leave non-episode positions missing
    episode_id = (
        episode_start.cumsum()
        .astype('Int64')
        .where(episode)
    )

    # Give every entry in an episode that episode's maximum value
    episode_peak = (
        index_series.groupby(episode_id).transform('max')
    )

    # Preserve missing input values as unknown episode status
    episode = episode.astype('boolean')
    episode = episode.mask(index_series.isna(), pd.NA)

    return pd.DataFrame({
        'episode': months.map(episode),
        'episode_id': months.map(episode_id),
        'episode_peak': months.map(episode_peak)
    })

        

def oni_classify(peak):
    if pd.isna(peak):
        return pd.NA
    elif peak >= 1.5:
        return 'Strong El Niño'
    elif 1.0 <= peak <= 1.4:
        return 'Moderate El Niño'
    elif 0.5 <= peak <= 0.9:
        return 'Weak El Niño'
    else:
        return 'Unclassified strength'

def roni_classify(peak):
    if pd.isna(peak):
        return pd.NA
    elif peak >= 2.0:
        return 'Very Strong El Niño'
    elif 1.5 <= peak < 2.0:
        return 'Strong El Niño'
    elif 1.0 <= peak < 1.5:
        return 'Moderate El Niño'
    elif 0.5 <= peak < 1.0:
        return 'Weak El Niño'
    else:
        return 'Unclassified strength'

#create columns and classify with helper functions

oni_results = identify_runs(raw_table_df, 'ONI')
roni_results = identify_runs(raw_table_df, 'RONI')

raw_table_df['ONI_episode'] = oni_results['episode']
raw_table_df['ONI_episode_id'] = oni_results['episode_id']
raw_table_df['ONI_episode_peak'] = oni_results['episode_peak']

raw_table_df['RONI_episode'] = roni_results['episode']
raw_table_df['RONI_episode_id'] = roni_results['episode_id']
raw_table_df['RONI_episode_peak'] = roni_results['episode_peak']

raw_table_df['ONI_episode_strength'] = (
    raw_table_df['ONI_episode_peak'].apply(oni_classify)
)

raw_table_df['RONI_episode_strength'] = (
    raw_table_df['RONI_episode_peak'].apply(roni_classify)
)
#uncomment to check out the new columns
display(raw_table_df)

,station,time,TMAX,TMAX_q,TMIN,TMIN_q,PRCP,PRCP_q,MDPR,MDPR_q,...,RONI,TNI,ONI_episode,ONI_episode_id,ONI_episode_peak,RONI_episode,RONI_episode_id,RONI_episode_peak,ONI_episode_strength,RONI_episode_strength
0,USW00014926,1904-09-01,NaN,False,NaN,False,0.0,False,NaN,False,...,1.04,0.584,True,1,1.6,True,1,1.9,Strong El Niño,Strong El Niño
1,USW00014926,1904-09-02,NaN,False,NaN,False,41.4,False,NaN,False,...,1.04,0.584,True,1,1.6,True,1,1.9,Strong El Niño,Strong El Niño
2,USW00014926,1904-09-03,NaN,False,NaN,False,48.5,False,NaN,False,...,1.04,0.584,True,1,1.6,True,1,1.9,Strong El Niño,Strong El Niño
3,USW00014926,1904-09-04,NaN,False,NaN,False,0.0,False,NaN,False,...,1.04,0.584,True,1,1.6,True,1,1.9,Strong El Niño,Strong El Niño
4,USW00014926,1904-09-05,NaN,False,NaN,False,0.0,False,NaN,False,...,1.04,0.584,True,1,1.6,True,1,1.9,Strong El Niño,Strong El Niño
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298952,USW00014920,2026-09-23,20.6,False,6.7,False,0.0,False,NaN,False,...,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
298953,USW00014920,2026-09-24,21.1,False,9.4,False,0.3,False,NaN,False,...,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
298954,USW00014920,2026-09-25,22.8,False,15.0,False,0.0,False,NaN,False,...,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
298955,USW00014920,2026-09-26,22.2,False,11.7,False,0.0,False,NaN,False,...,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN
298956,USW00014920,2026-09-27,17.2,False,15.0,False,0.0,False,NaN,False,...,NaN,NaN,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaN,NaN

In [102]:
#select djf obs only,
#group obs by year,
#separate nino and no nino months,
#and group stations


#helper functions
def winter_year(date):
   if date.month==12:
       return date.year+1
   else:
       return date.year

def identify_ninos(df, index):
    status = df[f'{index}_episode']
    return df[status.eq(True).fillna(False)]


def indentify_non_ninos(df, index):
    status = df[f'{index}_episode']
    return df[status.eq(False).fillna(False)]
            

#first store djf obs only
raw_table_df['time']=pd.to_datetime(raw_table_df['time'])
djf_obs = raw_table_df[raw_table_df['time'].dt.month.isin([12, 1, 2])].copy()

#creates the winter year column in the dataframe
djf_obs['winter_year']=djf_obs['time'].apply(winter_year)


#find all nino rows according to oni
yes_nino_oni=identify_ninos(djf_obs, 'ONI')
no_nino_oni=indentify_non_ninos(djf_obs, 'ONI')

#find all non el nino rows according to oni
yes_nino_roni=identify_ninos(djf_obs, 'RONI')
no_nino_roni=indentify_non_ninos(djf_obs, 'RONI')



#average seasonal precip in inches


#sum seasonal snowfall in inches

#average seasonal temperature

#sum of el nino varities (strong nuetral etc)

In [105]:
#table calculations

columns = [
    'winter_year',
    'ONI_episode',
    'ONI_episode_strength',
    'RONI_episode',
    'RONI_episode_strength'
]

winter_table = (
    djf_obs.loc[djf_obs['time'].dt.month == 1, columns]
    .drop_duplicates(subset='winter_year')
    .set_index('winter_year')
    .sort_index()
)
#winter_table = winter_table.loc[1950:2026].copy() this will produce the 'Kenny Table'
# Retain winters with no January observations as unclassified.
all_winters = pd.Index(
    sorted(djf_obs['winter_year'].dropna().unique()),
    name='winter_year'
)

winter_table = winter_table.reindex(all_winters)

for index in ['ONI', 'RONI']:
    status = winter_table[f'{index}_episode'].astype('boolean')

    yes = status.eq(True).fillna(False)
    no = status.eq(False).fillna(False)
    unknown = status.isna()

    label_column = f'{index}_winter_class'
    winter_table[label_column] = 'Unclassified'

    winter_table.loc[yes, label_column] = winter_table.loc[
        yes, f'{index}_episode_strength'
    ]
    winter_table.loc[no, label_column] = 'No El Niño episode at DJF'

    known_years = winter_table.index[status.notna()]

    if len(known_years) > 0:
        start_year = known_years.min()
        end_year = known_years.max()

        print(
            'According to the', index, 'there were',
            int(yes.sum()),
            'winters coinciding with El Niño conditions in the Pacific between',
            start_year, 'and', end_year
        )

        print(
            'According to the', index, 'there were',
            int(no.sum()),
            'winters not coinciding with El Niño conditions in the Pacific between',
            start_year, 'and', end_year
        )
    else:
        print('No winters could be classified using the', index)

    print('Winters with unknown episode status:', int(unknown.sum()))
    print()

According to the ONI there were 37 winters coinciding with El Niño conditions in the Pacific between 1892 and 2026
According to the ONI there were 85 winters not coinciding with El Niño conditions in the Pacific between 1892 and 2026
Winters with unknown episode status: 1

According to the RONI there were 40 winters coinciding with El Niño conditions in the Pacific between 1892 and 2026
According to the RONI there were 82 winters not coinciding with El Niño conditions in the Pacific between 1892 and 2026
Winters with unknown episode status: 1

In [46]:
#form data viz