# Download ENSO Indicies Data

This script downloads ONI, RONI, and TNI historical data  
and compiles them into a data frame 
then converts  
then stores in the indicies_data/first_pass folder  

v1.0 designates the very first iteration that has no (known) bugs    
v1.0 should contribute to a reproducible workflow on any machine with the other 1.0 notebooks

In [1]:
#dependencies
from pathlib import Path
import pandas as pd

In [2]:
#makes data directory structure
indicies_dir=Path("../indicies_data/first_pass")
indicies_dir.mkdir(parents=True, exist_ok=True)

# save name of final product
output_roni_oni_tni_indicies= indicies_dir/'enso_historical_indicies.csv'

In [3]:
#get the data sources from NOAA and University of Miami into dataframes 

'''
direct web->notebook access encountered certification errors I could not resolve 
this data was manually placed into ../indicies_data/first_pass

oni_historic        ->     https://bmcnoldy.earth.miami.edu/tropics/oni/ONI_NINO34_v6.txt
tni_historic_csv    ->     https://psl.noaa.gov/data/timeseries/month/data/tni.long.csv
tni_historic_nc     ->     https://psl.noaa.gov/data/timeseries/month/data/tni.long.nc (this set may not be used in the workflow)
roni_historic       ->     https://bmcnoldy.earth.miami.edu/tropics/roni/RONI_NINO34_v6.txt
'''



#assign file paths
oni_historic=Path(indicies_dir/'ONI_NINO34_v6.txt')
roni_historic=Path(indicies_dir/'RONI_NINO34_v6.txt')
tni_historic=Path(indicies_dir/'tni.long.csv')

#read txt/csv files and init their variables

#oni
oni_historic_df=pd.read_csv(
    oni_historic,
    skiprows=10,
    sep=r"\s+",
    na_values=[-99.99],
)

#roni
roni_historic_df=pd.read_csv(
    roni_historic,
    skiprows=10,
    sep=r"\s+",
    na_values=[-99.99],
    )

#tni
tni_historic_df = pd.read_csv(
    tni_historic,
    header=0,
    names=["Date", "TNI"],      #replaces link in header with just date and tni
    parse_dates=["Date"],       #tells pandas these are dates 
    na_values=[-99.99,-9999],
)

#read nc file
#xr.open_dataset(tni_historic_nc)

In [9]:
#uncomment this to see the data dims and range

display(tni_historic_df)
display(oni_historic_df)
display(roni_historic_df)

           Date    TNI
0    1870-01-01    NaN
1    1870-02-01    NaN
2    1870-03-01  0.834
3    1870-04-01  1.127
4    1870-05-01  0.863
...         ...    ...
1879 2026-08-01    NaN
1880 2026-09-01    NaN
1881 2026-10-01    NaN
1882 2026-11-01    NaN
1883 2026-12-01    NaN

[1884 rows x 2 columns]

,YEAR,MON/MMM,NINO34_MEAN,NINO34_CLIM,NINO34_ANOM,ONI,PHASE,Date
0,1850,1,25.99,NaN,NaN,NaN,M,1850-01-01
1,1850,2,25.36,NaN,NaN,NaN,M,1850-02-01
2,1850,3,25.09,NaN,NaN,NaN,M,1850-03-01
3,1850,4,26.23,NaN,NaN,NaN,M,1850-04-01
4,1850,5,27.41,NaN,NaN,NaN,M,1850-05-01
...,...,...,...,...,...,...,...,...
2119,2026,8,29.04,26.87,2.17,NaN,M,2026-08-01
2120,2026,9,NaN,26.71,NaN,NaN,M,2026-09-01
2121,2026,10,NaN,26.71,NaN,NaN,M,2026-10-01
2122,2026,11,NaN,26.71,NaN,NaN,M,2026-11-01
2123,2026,12,NaN,26.53,NaN,NaN,M,2026-12-01

,YEAR,MON,NINO34_MEAN,NINO34_CLIM,TROP_MEAN,TROP_CLIM,RONI,PHASE,Date
0,1850,1,25.99,26.61,26.65,27.09,NaN,M,1850-01-01
1,1850,2,25.36,26.80,26.84,27.25,-1.14,L,1850-02-01
2,1850,3,25.09,27.31,26.84,27.59,-1.51,L,1850-03-01
3,1850,4,26.23,27.90,27.07,27.85,-1.16,L,1850-04-01
4,1850,5,27.41,27.98,27.36,27.78,-0.69,L,1850-05-01
...,...,...,...,...,...,...,...,...,...
2115,2026,4,28.23,27.90,28.27,27.85,-0.04,N,2026-04-01
2116,2026,5,28.81,27.98,28.23,27.78,0.51,E,2026-05-01
2117,2026,6,29.17,27.76,27.94,27.37,1.00,E,2026-06-01
2118,2026,7,29.06,27.31,27.54,26.92,1.36,E,2026-07-01
2119,2026,8,29.04,26.90,27.42,26.72,NaN,M,2026-08-01

In [5]:
#create single date column for ONI and for RONI
#align date's of the data 

'''
ONI and RONI index have separate year and month columns
this TNI dataset also only goes back to 1870
'''

#form a single date column for oni 
oni_historic_df['Date']=pd.to_datetime(
    {
        'year':oni_historic_df['YEAR'],
        'month':oni_historic_df['MON/MMM'],
        'day':1
    }
)


#form a single date colum for roni 
roni_historic_df['Date']=pd.to_datetime(
    {
        'year':roni_historic_df['YEAR'],
        'month':roni_historic_df['MON'],
        'day':1
    }
)

In [10]:
# uncomment this to see how the dataframes were modified
display(tni_historic_df)
display(oni_historic_df)
display(roni_historic_df)

           Date    TNI
0    1870-01-01    NaN
1    1870-02-01    NaN
2    1870-03-01  0.834
3    1870-04-01  1.127
4    1870-05-01  0.863
...         ...    ...
1879 2026-08-01    NaN
1880 2026-09-01    NaN
1881 2026-10-01    NaN
1882 2026-11-01    NaN
1883 2026-12-01    NaN

[1884 rows x 2 columns]

,YEAR,MON/MMM,NINO34_MEAN,NINO34_CLIM,NINO34_ANOM,ONI,PHASE,Date
0,1850,1,25.99,NaN,NaN,NaN,M,1850-01-01
1,1850,2,25.36,NaN,NaN,NaN,M,1850-02-01
2,1850,3,25.09,NaN,NaN,NaN,M,1850-03-01
3,1850,4,26.23,NaN,NaN,NaN,M,1850-04-01
4,1850,5,27.41,NaN,NaN,NaN,M,1850-05-01
...,...,...,...,...,...,...,...,...
2119,2026,8,29.04,26.87,2.17,NaN,M,2026-08-01
2120,2026,9,NaN,26.71,NaN,NaN,M,2026-09-01
2121,2026,10,NaN,26.71,NaN,NaN,M,2026-10-01
2122,2026,11,NaN,26.71,NaN,NaN,M,2026-11-01
2123,2026,12,NaN,26.53,NaN,NaN,M,2026-12-01

,YEAR,MON,NINO34_MEAN,NINO34_CLIM,TROP_MEAN,TROP_CLIM,RONI,PHASE,Date
0,1850,1,25.99,26.61,26.65,27.09,NaN,M,1850-01-01
1,1850,2,25.36,26.80,26.84,27.25,-1.14,L,1850-02-01
2,1850,3,25.09,27.31,26.84,27.59,-1.51,L,1850-03-01
3,1850,4,26.23,27.90,27.07,27.85,-1.16,L,1850-04-01
4,1850,5,27.41,27.98,27.36,27.78,-0.69,L,1850-05-01
...,...,...,...,...,...,...,...,...,...
2115,2026,4,28.23,27.90,28.27,27.85,-0.04,N,2026-04-01
2116,2026,5,28.81,27.98,28.23,27.78,0.51,E,2026-05-01
2117,2026,6,29.17,27.76,27.94,27.37,1.00,E,2026-06-01
2118,2026,7,29.06,27.31,27.54,26.92,1.36,E,2026-07-01
2119,2026,8,29.04,26.90,27.42,26.72,NaN,M,2026-08-01

In [7]:
#combine dataframes of oni and roni
#outer joins on the new column (key) DATE

oni_roni_historic_df=pd.merge(
    left=oni_historic_df[["Date","ONI"]], 
    right=roni_historic_df[["Date","RONI"]],
    on='Date', 
    how='outer'
)

#combine oni/roni df with tni

oni_roni_tni_historic_df=pd.merge(
    left=oni_roni_historic_df,
    right=tni_historic_df,
    on='Date',
    how='outer'
)

In [11]:
''' 
Here is the final product
a dataframe of all three indicies
aligned by date
'''
oni_roni_tni_historic_df["Date"] = pd.to_datetime(
    oni_roni_tni_historic_df["Date"]
)
oni_roni_tni_historic_df["Year"] = oni_roni_tni_historic_df["Date"].dt.year


oni_roni_tni_historic_df.to_csv(output_roni_oni_tni_indicies)

#uncomment to see
display(oni_roni_tni_historic_df)

           Date  ONI  RONI  TNI  Year
0    1850-01-01  NaN   NaN  NaN  1850
1    1850-02-01  NaN -1.14  NaN  1850
2    1850-03-01  NaN -1.51  NaN  1850
3    1850-04-01  NaN -1.16  NaN  1850
4    1850-05-01  NaN -0.69  NaN  1850
...         ...  ...   ...  ...   ...
2119 2026-08-01  NaN   NaN  NaN  2026
2120 2026-09-01  NaN   NaN  NaN  2026
2121 2026-10-01  NaN   NaN  NaN  2026
2122 2026-11-01  NaN   NaN  NaN  2026
2123 2026-12-01  NaN   NaN  NaN  2026

[2124 rows x 5 columns]